### ISSUE TITLE
关于英文到中文场景迁移

### ISSUE THREAD

**Issue by 123newday** [shaoyangxu/DSG-SEG#1]
很感谢您的开源分享，目前我正在您的项目基础上做英文到中文的迁移，以实现中文场景下的主题分割。
想请问下您后续是否调研过此模型迁移到中文场景的可行性？或者是否有一些初步的方案？期待和您交流。

**Comment by shaoyangxu** [comment]
@123newday 这套代码用于中文数据集应该也可行，需要修改一下[数据的读取](https://github.com/beiweixiaoxu/DSG-SEG/tree/master/data)以及使用[中文的词向量。](https://github.com/beiweixiaoxu/DSG-SEG/tree/master/encoder)

**Comment by 123newday** [comment]
OKOK 我先试试
